### ISSUE TITLE
Diagrams for "authenticated/verified group/onion key lookup"

### ISSUE THREAD

**Issue by hpk42** [nextleap-project/countermitm#29]
Currently the discussion of the verified contact/group protocols do not have diagrams such as the gossip section.  Arguably diagrams for the contact/group/onion protocols are more important.

**Comment by azul** [comment]
We have a diagram for the verified contact case now.
The ones for verirfied groups are very similar.
I will tackle the one for onion key lookup as part of the clarification in #49.
