### ISSUE TITLE
lack of checking when Bob knows Alice's FP

### ISSUE THREAD

**Issue by carmelatroncoso** [nextleap-project/countermitm#44]
>    a) If Bob's device knows a key that matches ``Alice_FP``  the protocol continues with 4b)

In step 4b) Bob just sends back his key, but he does not check that the email received is the same as the one he had associated to the value ``Alice_FP`` he had stored. Doesn't this open the door to an attack? As long as I know Alice's FP I can get Bob to engage. Am I missing something?

**Comment by hpk42** [comment]
to fix this issue isn't it sufficient to write: 

"a) If bob's device already verified that Alice's e-mail address is associated with ``Alice_FP`` the protocol continus with 4b)"

**Comment by azul** [comment]
The approach sounds good. I would use a different term than 'verified'.
I think the main usecase here is verifying a contact i already have an autocrypt key for.

The other question for me is if we want to explicitely ask the user to verify that the email address matches the person they are talking to. I think we don't neet to but should make it very obvious who one is verifying by highlighting the email address during the process.
