### ISSUE TITLE
discuss use cases of group/contact protocols

### ISSUE THREAD

**Issue by hpk42** [nextleap-project/countermitm#65]
there are multiple use cases wrt to group/contact invite/join: 

- initiate a verified chat contact/group in a public room (assume a powerful in-room camera adversary)

- initiate a verified chat contact/group in a concealed setting (no observer assumed) 

- let people contact/join via print-outs, eg business cards.  

These use cases lead to different demands on "freshness" and dis/allowing re-use of codes and should be discussed more explicitely in countermitm.

**Comment by azul** [comment]
#66 addresses the related protocol properties (in particular confidential oob vs. non-confidential). A discussion of the use cases is still missing though.

**Comment by azul** [comment]
I think we elaborate enough about this on the protocol level.
Usecase discussion probably better fits within the context of concrete implimentations such as delta.chat.
@hpk42, what do you think? can we close this?

**Comment by hpk42** [comment]
yip, agreed.
